# backend/app/services/content_service.py

from typing import Any, Dict, Optional
import json
import os

from sqlalchemy.orm import Session

from ...database import SessionLocal  # only if you need it directly
from ...models import ContentVersion

# Simple admin API key
ADMIN_API_KEY = os.getenv("ADMIN_API_KEY", "changeme-admin-key")


def get_default_content() -> Dict[str, Any]:
    return {
        "hero": {
            "headline": "Helping clients build modern solutions.",
            "subheadline": "Short value prop about what the business actually does.",
            "primaryCtaLabel": "Get in touch",
            "primaryCtaHref": "/contact",
            # NEW: optional secondary CTA used by the sleek layout
            "secondaryCtaLabel": "View services",
            "secondaryCtaHref": "/services",
            # NEW: which homepage layout to use by default
            # "classic" or "sleek"
            "layoutVariant": "classic",
        },
        "about": {
            "title": "About Us",
            "body": [
                "Tell the story of the business, mission, vision, and what makes them different.",
                "Add timeline, credentials, certifications, or leadership bios here later.",
            ],
        },
        "services": [
            {
                "title": "Service One",
                "description": "Short description of service one.",
                # NEW: tagline used in the sleek layout (falls back to 'Service')
                "tagline": "Advisory",
            },
            {
                "title": "Service Two",
                "description": "Short description of service two.",
                "tagline": "Engineering",
            },
            {
                "title": "Service Three",
                "description": "Short description of service three.",
                "tagline": "Operations",
            },
        ],
        "careers": {
            "intro": "We hire smart, self-directed people who thrive in modern cloud, security, and consulting environments.",
            "positions": [
                {
                    "id": "lead-security-software-engineer",
                    "title": "Lead Security Software Engineer",
                    "summary": "Lead small, senior teams shipping secure, cloud-native systems for mission-critical clients.",
                    "tags": ["Security", "Cloud", "Full-Stack", "Leadership"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Senior",
                    "tagline": "Mission-critical platforms",
                    "salaryRange": "$165k–$210k USD",
                },
                {
                    "id": "senior-platform-devsecops-engineer",
                    "title": "Senior Platform / DevSecOps Engineer",
                    "summary": "Own CI/CD, infrastructure-as-code, and platform reliability across multiple client environments.",
                    "tags": ["DevSecOps", "Platform", "Automation"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "hybrid",
                    "level": "Senior",
                    "tagline": "Delivery & reliability",
                    "salaryRange": "$150k–$190k USD",
                },
                {
                    "id": "staff-backend-engineer-python",
                    "title": "Staff Backend Engineer (Python)",
                    "summary": "Design and implement secure, well-instrumented APIs and services with Python and modern frameworks.",
                    "tags": ["Backend", "APIs", "Python"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Staff",
                    "tagline": "APIs & data pipelines",
                    "salaryRange": "$160k–$205k USD",
                },
                {
                    "id": "senior-frontend-engineer-react",
                    "title": "Senior Frontend Engineer (React)",
                    "summary": "Build accessible, responsive frontends and design systems for internal tools and client-facing portals.",
                    "tags": ["Frontend", "React", "Design Systems"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "hybrid",
                    "level": "Senior",
                    "tagline": "Design systems & UX",
                    "salaryRange": "$145k–$185k USD",
                },
                {
                    "id": "full-stack-engineer-node-react",
                    "title": "Full-Stack Engineer (Node/React)",
                    "summary": "Ship end-to-end features across backend APIs, frontends, and cloud infrastructure.",
                    "tags": ["Full-Stack", "Node.js", "React"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "End-to-end delivery",
                    "salaryRange": "$135k–$175k USD",
                },
                {
                    "id": "site-reliability-engineer",
                    "title": "Site Reliability Engineer",
                    "summary": "Design SLOs, improve observability, and keep multi-tenant platforms healthy under real-world load.",
                    "tags": ["SRE", "Observability", "Reliability"],
                    "team": "Engineering",
                    "location": "Hybrid – DC / Baltimore",
                    "workMode": "onsite",
                    "level": "Senior",
                    "tagline": "Reliability & observability",
                    "salaryRange": "$145k–$185k USD",
                },
                {
                    "id": "cloud-infrastructure-engineer-aws",
                    "title": "Cloud Infrastructure Engineer (AWS)",
                    "summary": "Build secure, automated AWS foundations using Terraform, container platforms, and cloud-native services.",
                    "tags": ["Cloud", "AWS", "Terraform"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "Cloud foundations",
                    "salaryRange": "$135k–$175k USD",
                },
                {
                    "id": "data-engineer",
                    "title": "Data Engineer",
                    "summary": "Design and maintain data pipelines, warehouses, and models that power analytics and decision-making.",
                    "tags": ["Data", "ETL", "Analytics"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "other",
                    "level": "Mid–Senior",
                    "tagline": "Data platforms",
                    "salaryRange": "$135k–$175k USD",
                },
                {
                    "id": "machine-learning-engineer",
                    "title": "Machine Learning Engineer",
                    "summary": "Productionize ML models, build inference services, and integrate AI into secure client workflows.",
                    "tags": ["ML", "MLOps", "Data"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "ML & MLOps",
                    "salaryRange": "$145k–$190k USD",
                },
                {
                    "id": "security-automation-engineer",
                    "title": "Security Automation Engineer",
                    "summary": "Automate detection, response, and compliance checks across cloud and application estates.",
                    "tags": ["Security", "Automation", "Tooling"],
                    "team": "Security",
                    "location": "Remote (US)",
                    "workMode": "hybrid",
                    "level": "Mid–Senior",
                    "tagline": "Security tooling & automation",
                    "salaryRange": "$140k–$180k USD",
                },
                {
                    "id": "qa-automation-engineer",
                    "title": "QA Automation Engineer",
                    "summary": "Build and maintain automated test suites that keep platforms stable as they evolve.",
                    "tags": ["QA", "Automation", "Testing"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid",
                    "tagline": "Quality & test automation",
                    "salaryRange": "$115k–$145k USD",
                },
                {
                    "id": "mobile-engineer",
                    "title": "Mobile Engineer",
                    "summary": "Develop secure, performant mobile experiences that complement our web and platform offerings.",
                    "tags": ["Mobile", "iOS/Android"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "other",
                    "level": "Mid–Senior",
                    "tagline": "Mobile experiences",
                    "salaryRange": "$130k–$170k USD",
                },
                {
                    "id": "staff-architect-cloud-security",
                    "title": "Staff Architect (Cloud & Security)",
                    "summary": "Set technical direction for cloud and security architectures across high-impact programs.",
                    "tags": ["Architecture", "Security", "Cloud", "Leadership"],
                    "team": "Security",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Staff",
                    "tagline": "Architecture & strategy",
                    "salaryRange": "$180k–$230k USD",
                },
                {
                    "id": "principal-security-advisor",
                    "title": "Principal Security Advisor",
                    "summary": "Work directly with executives to shape security strategy, roadmaps, and investment priorities.",
                    "tags": ["Advisory", "Security", "Executive"],
                    "team": "Advisory",
                    "location": "Remote (US)",
                    "workMode": "other",
                    "level": "Principal",
                    "tagline": "Executive advisory",
                    "salaryRange": "$190k–$250k USD",
                },
                {
                    "id": "application-security-engineer",
                    "title": "Application Security Engineer",
                    "summary": "Embed security into the SDLC, perform secure code reviews, and partner closely with product teams.",
                    "tags": ["AppSec", "SDLC", "Security"],
                    "team": "Security",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "Secure SDLC",
                    "salaryRange": "$140k–$185k USD",
                },
                {
                    "id": "grc-analyst",
                    "title": "GRC Analyst",
                    "summary": "Support governance, risk, and compliance work across NIST, FedRAMP, and related frameworks.",
                    "tags": ["GRC", "Compliance", "Risk"],
                    "team": "Security",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid",
                    "tagline": "Governance & compliance",
                    "salaryRange": "$115k–$145k USD",
                },
                {
                    "id": "security-compliance-manager",
                    "title": "Security Compliance Manager",
                    "summary": "Own audits, evidence collection, and continuous compliance for regulated client environments.",
                    "tags": ["Compliance", "Security", "Leadership"],
                    "team": "Security",
                    "location": "Remote (US)",
                    "workMode": "hybrid",
                    "level": "Senior",
                    "tagline": "Compliance leadership",
                    "salaryRange": "$140k–$185k USD",
                },
                {
                    "id": "iam-engineer",
                    "title": "IAM Engineer",
                    "summary": "Design and operate identity, access, and federation patterns for multi-tenant environments.",
                    "tags": ["IAM", "Security", "Identity"],
                    "team": "Security",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "Identity & access",
                    "salaryRange": "$130k–$170k USD",
                },
                {
                    "id": "technical-project-manager",
                    "title": "Technical Project Manager",
                    "summary": "Coordinate teams, scope, and timelines so complex engineering work lands smoothly.",
                    "tags": ["Delivery", "Project Management"],
                    "team": "Client Services",
                    "location": "Hybrid – DC / Baltimore",
                    "workMode": "hybrid",
                    "level": "Mid–Senior",
                    "tagline": "Delivery leadership",
                    "salaryRange": "$130k–$170k USD",
                },
                {
                    "id": "delivery-manager",
                    "title": "Delivery Manager",
                    "summary": "Own the health of multi-stream engagements and ensure we repeatedly ship outcomes, not noise.",
                    "tags": ["Delivery", "Client Services", "Leadership"],
                    "team": "Client Services",
                    "location": "Hybrid – DC / Baltimore",
                    "workMode": "onsite",
                    "level": "Senior",
                    "tagline": "Engagement leadership",
                    "salaryRange": "$140k–$185k USD",
                },
                {
                    "id": "product-manager-platform",
                    "title": "Product Manager (Platform)",
                    "summary": "Translate client needs into platform capabilities and roadmap bets that compound over time.",
                    "tags": ["Product", "Platform", "Strategy"],
                    "team": "Client Services",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "Product strategy",
                    "salaryRange": "$135k–$175k USD",
                },
                {
                    "id": "ux-designer",
                    "title": "UX Designer",
                    "summary": "Design calm, clear interfaces for technically complex workflows used by real teams every day.",
                    "tags": ["UX", "Design", "Product"],
                    "team": "Design",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "Product design",
                    "salaryRange": "$120k–$155k USD",
                },
                {
                    "id": "technical-writer",
                    "title": "Technical Writer",
                    "summary": "Create clear, accurate docs, runbooks, and client-facing artifacts that make complex systems legible.",
                    "tags": ["Writing", "Documentation", "Enablement"],
                    "team": "Client Services",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid",
                    "tagline": "Docs & enablement",
                    "salaryRange": "$95k–$125k USD",
                },
                {
                    "id": "customer-success-manager",
                    "title": "Customer Success Manager",
                    "summary": "Partner with clients to ensure our platforms and services land, stick, and grow over time.",
                    "tags": ["Customer Success", "Consulting"],
                    "team": "Client Services",
                    "location": "Remote (US)",
                    "workMode": "hybrid",
                    "level": "Mid–Senior",
                    "tagline": "Customer outcomes",
                    "salaryRange": "$115k–$145k USD",
                },
                {
                    "id": "junior-software-engineer",
                    "title": "Junior Software Engineer",
                    "summary": "Work with senior engineers to ship features, learn modern tooling, and grow into a full-stack role.",
                    "tags": ["Junior", "Engineering", "Full-Stack"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Junior",
                    "tagline": "Early career engineering",
                    "salaryRange": "$85k–$105k USD",
                },
                {
                    "id": "junior-cloud-engineer",
                    "title": "Junior Cloud Engineer",
                    "summary": "Support cloud foundations work, IaC modules, and environment provisioning alongside senior staff.",
                    "tags": ["Cloud", "IaC", "Junior"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Junior",
                    "tagline": "Early career cloud",
                    "salaryRange": "$80k–$100k USD",
                },
                {
                    "id": "security-analyst",
                    "title": "Security Analyst",
                    "summary": "Help monitor environments, triage findings, and support investigations under senior guidance.",
                    "tags": ["Security", "Analysis"],
                    "team": "Security",
                    "location": "Remote (US)",
                    "workMode": "other",
                    "level": "Junior–Mid",
                    "tagline": "Security operations support",
                    "salaryRange": "$90k–$120k USD",
                },
                {
                    "id": "help-desk-engineer",
                    "title": "Help Desk Engineer",
                    "summary": "Support internal teams with access, tooling, and endpoint issues in a security-conscious way.",
                    "tags": ["Support", "IT", "Operations"],
                    "team": "Operations",
                    "location": "Hybrid – DC / Baltimore",
                    "workMode": "onsite",
                    "level": "Junior–Mid",
                    "tagline": "Internal IT support",
                    "salaryRange": "$70k–$95k USD",
                },
                {
                    "id": "it-operations-engineer",
                    "title": "IT Operations Engineer",
                    "summary": "Maintain core internal systems, endpoints, and secure configurations for a hybrid workforce.",
                    "tags": ["IT", "Operations", "Security"],
                    "team": "Operations",
                    "location": "Hybrid – DC / Baltimore",
                    "workMode": "hybrid",
                    "level": "Mid",
                    "tagline": "Internal infrastructure",
                    "salaryRange": "$95k–$125k USD",
                },
                {
                    "id": "observability-engineer",
                    "title": "Observability Engineer",
                    "summary": "Own logging, metrics, and tracing stacks so teams can see and fix issues before users notice.",
                    "tags": ["Observability", "Monitoring", "SRE"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "Telemetry & insight",
                    "salaryRange": "$130k–$170k USD",
                },
                {
                    "id": "developer-relations-engineer",
                    "title": "Developer Relations Engineer",
                    "summary": "Create content, examples, and tooling that help developers successfully adopt our platforms.",
                    "tags": ["DevRel", "Content", "Developer Experience"],
                    "team": "Client Services",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid–Senior",
                    "tagline": "Developer experience",
                    "salaryRange": "$120k–$155k USD",
                },
                {
                    "id": "solutions-architect",
                    "title": "Solutions Architect",
                    "summary": "Design pragmatic, secure solutions that bridge client requirements and our technical capabilities.",
                    "tags": ["Architecture", "Pre-Sales", "Consulting"],
                    "team": "Advisory",
                    "location": "Remote (US)",
                    "workMode": "other",
                    "level": "Senior",
                    "tagline": "Solution design",
                    "salaryRange": "$150k–$195k USD",
                },
                {
                    "id": "program-manager",
                    "title": "Program Manager",
                    "summary": "Oversee multi-team programs, manage dependencies, and keep stakeholders aligned on outcomes.",
                    "tags": ["Program Management", "Delivery"],
                    "team": "Client Services",
                    "location": "Hybrid – DC / Baltimore",
                    "workMode": "hybrid",
                    "level": "Senior",
                    "tagline": "Multi-stream leadership",
                    "salaryRange": "$145k–$185k USD",
                },
                {
                    "id": "business-analyst-consulting",
                    "title": "Business Analyst (Consulting)",
                    "summary": "Work with clients to clarify goals, map processes, and turn fuzzy ideas into concrete requirements.",
                    "tags": ["Analysis", "Consulting", "Requirements"],
                    "team": "Client Services",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid",
                    "tagline": "Client discovery",
                    "salaryRange": "$105k–$135k USD",
                },
                {
                    "id": "hr-generalist",
                    "title": "HR Generalist",
                    "summary": "Support hiring, onboarding, and people operations in a remote-first, high-trust environment.",
                    "tags": ["HR", "People Operations"],
                    "team": "People",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid",
                    "tagline": "People operations",
                    "salaryRange": "$85k–$110k USD",
                },
                {
                    "id": "recruiting-lead",
                    "title": "Recruiting Lead",
                    "summary": "Run a respectful, signal-driven recruiting process that values candidates’ time and experience.",
                    "tags": ["Recruiting", "Talent"],
                    "team": "People",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Senior",
                    "tagline": "Talent acquisition",
                    "salaryRange": "$110k–$145k USD",
                },
                {
                    "id": "finance-operations-analyst",
                    "title": "Finance Operations Analyst",
                    "summary": "Help track project financials, margins, and forecasts so we can make smart, sustainable decisions.",
                    "tags": ["Finance", "Operations"],
                    "team": "Operations",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Mid",
                    "tagline": "Financial operations",
                    "salaryRange": "$95k–$125k USD",
                },
                {
                    "id": "office-operations-manager",
                    "title": "Office & Operations Manager",
                    "summary": "Keep our physical spaces, events, and internal operations running smoothly for hybrid teams.",
                    "tags": ["Operations", "Office Management"],
                    "team": "Operations",
                    "location": "Hybrid – DC / Baltimore",
                    "workMode": "onsite",
                    "level": "Mid–Senior",
                    "tagline": "On-the-ground operations",
                    "salaryRange": "$90k–$120k USD",
                },
                {
                    "id": "engineering-intern",
                    "title": "Engineering Intern",
                    "summary": "Join a small squad, ship scoped features, and learn modern engineering practices in the real world.",
                    "tags": ["Internship", "Engineering"],
                    "team": "Engineering",
                    "location": "Remote (US)",
                    "workMode": "remote",
                    "level": "Intern",
                    "tagline": "Early career internship",
                    "salaryRange": "$30–$40/hr USD",
                },
                {
                    "id": "general-application",
                    "title": "General Application",
                    "summary": "If your skill set doesn’t quite match a listed role but aligns with our work, we still want to hear from you.",
                    "tags": ["General"],
                    "team": "General",
                    "location": "Remote (US)",
                    "workMode": "other",
                    "level": "All levels",
                    "tagline": "Open talent network",
                    "salaryRange": "Varies by role and level",
                },
            ],
        },
        "contact": {
            "intro": "Have questions or want to discuss a project? Send us a message.",
            "email": "info@example.com",
            "phone": "+1 (555) 555-5555",
            "address": "123 Business Street, City, State",
        },
    }


def load_content_from_db(db: Session) -> Dict[str, Any]:
    """
    Get the latest content version. If none exists, seed with defaults.
    """
    latest: Optional[ContentVersion] = (
        db.query(ContentVersion).order_by(ContentVersion.version.desc()).first()
    )

    if latest is None:
        default = get_default_content()
        seed = ContentVersion(version=1, content_json=json.dumps(default))
        db.add(seed)
        db.commit()
        db.refresh(seed)
        return default

    return json.loads(latest.content_json)


def save_content_to_db(db: Session, new_content: Dict[str, Any]) -> int:
    """
    Save a new version of the content and return version number.
    """
    latest: Optional[ContentVersion] = (
        db.query(ContentVersion).order_by(ContentVersion.version.desc()).first()
    )

    new_version = 1 if latest is None else latest.version + 1

    record = ContentVersion(
        version=new_version,
        content_json=json.dumps(new_content),
    )

    db.add(record)
    db.commit()
    db.refresh(record)

    return new_version
